In [14]:
from keras.models import load_model
import tensorflow as tf
tf.reset_default_graph()

from PIL import Image
import os,glob,numpy as np
from keras.models import load_model
import numpy as np
from keras import backend as K
import cv2

import os 
os.environ['CUDA_VISIBLE_DEVICES']= -1

TypeError: str expected, not int

In [10]:
K.clear_session()

In [11]:
image_dir = ('./emotion_edit/facetest')
model_dir =('./emotion_edit/model/vgg16avg.model')

In [12]:
model = load_model(model_dir,compile=False)

test_dir = image_dir
image_w =128
image_h =128

# face_cascade = cv.CascadeClassifier('../input/haarcascade/haarcascade_frontalface_default.xml')

T = []
filenames =[]
files = glob.glob(test_dir+ '/' + '*.*')


for i,f in enumerate(files):
    img = Image.open(f)
    img = img.convert("L")
    img = img.resize((image_w, image_h))
#     img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#     img = face_cascade.detectMultiScale(img,1.3,1)
    data = np.asarray(img)
    filenames.append(f)
#     print(filenames)
    print(data)
    T.append(data)
    print(T)

T= np.array(T)

model = load_model(model_dir) 
T = T.reshape(T.shape[0],128,128,1)

prediction = model.predict(T)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
cnt = 0

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)}) #>> 넘파이 출력옵션 변경하는것! (소수점3자리까지)
cnt = 0
for i in prediction:
    pre_ans = i.argmax()  # 예측 레이블  # argmax : 함수를 최대로 만들기 위한 x 값 --> 즉 첫번째에서는 3번째만 1이므로 2가 출력됨
    print(i)
    print(pre_ans)
    pre_ans_str = ''
    if pre_ans == 0: pre_ans_str = "afraid"
    elif pre_ans == 1: pre_ans_str = "anger"
    elif pre_ans == 2: pre_ans_str = "disgusted"
    elif pre_ans == 3: pre_ans_str = "happy"
    elif pre_ans == 4: pre_ans_str = "neutral"
    elif pre_ans == 5: pre_ans_str = "sad"
    
    else: pre_ans_str = "surprised"
    if i[0] >= 0.8 : print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[1] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[2] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[3] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[4] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[5] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[3] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")    
    cnt += 1




[[220 220 220 ... 183 206 201]
 [219 220 220 ... 188 207 170]
 [220 220 220 ... 200 204 164]
 ...
 [ 51  55  48 ... 213 213 213]
 [ 52  54  46 ... 213 213 214]
 [ 46  54  49 ... 213 213 213]]
[array([[220, 220, 220, ..., 183, 206, 201],
       [219, 220, 220, ..., 188, 207, 170],
       [220, 220, 220, ..., 200, 204, 164],
       ...,
       [ 51,  55,  48, ..., 213, 213, 213],
       [ 52,  54,  46, ..., 213, 213, 214],
       [ 46,  54,  49, ..., 213, 213, 213]], dtype=uint8)]
[[117 112 115 ...  82  91  88]
 [107  95 100 ... 114 116 112]
 [121 119 120 ... 114 106 118]
 ...
 [  9   8   6 ...   8   8   7]
 [ 12  13  11 ...  11   9   8]
 [ 17  11   9 ...   3   9   8]]
[array([[220, 220, 220, ..., 183, 206, 201],
       [219, 220, 220, ..., 188, 207, 170],
       [220, 220, 220, ..., 200, 204, 164],
       ...,
       [ 51,  55,  48, ..., 213, 213, 213],
       [ 52,  54,  46, ..., 213, 213, 214],
       [ 46,  54,  49, ..., 213, 213, 213]], dtype=uint8), array([[117, 112, 115, ...,  82

UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1_1/convolution}}]]
	 [[dense_5_1/Softmax/_745]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1_1/convolution}}]]
0 successful operations.
0 derived errors ignored.